Add a progress bar to show dataset progress
ecoacoustics/web-components pull request #173
Opened 2024-09-06 06:39 UTC by hudson-newey

# Add a progress bar to show dataset progress

A short description of the pull request

## Changes

### Features

- Add progress bar to verification grid to show how far through the dataset the user is

### Bug Fixes

None

### Code Quality

None

### Remaining Bugs / Unresolved Problems

## Visual Changes

## Documentation Examples

## Related Issues

Fixes: #163

## Additional Notes

## Final Checklist

- [ ] All commits messages are semver compliant
- [ ] Added relevant unit tests for new functionality
- [ ] Updated existing unit tests to reflect changes
- [ ] Code style is consistent with the project guidelines
- [ ] Documentation is updated to reflect the changes (if applicable)
- [ ] Link issues related to the PR
- [ ] Assign labels if you have permission
- [ ] Assign reviewers if you have permission
- [ ] Ensure that CI is passing
- [ ] Ensure that `pnpm lint` runs without any errors
- [ ] Ensure that `pnpm test` runs without any errors

2024-09-09 01:20 UTC, atruskie approved these changes
Looks great.  However we should consider what happens if the paging callback implemented does not provide a valid value to `totalItems`. What if it is 0 or negative? Or falsey? One way this (unbounded or incalculable totals) has been historically dealt with is a logarithmic function that never reaches 1, e.g.: https://www.wolframalpha.com/input?i=plot+0.93*log_10%281%2Bx*10%29+from+0+to+1

2024-09-09 01:32 UTC, hudson-newey commented on src/components/progress-bar/progress-bar.ts
> +  public historyHeadOffset = 0;
Yeah, `historyHead` is an offset relative to the completed head

2024-09-09 01:52 UTC, atruskie commented on src/components/progress-bar/progress-bar.ts
> +  public historyHeadOffset = 0;
oh weird. I'd have probably just modelled it as two counting from 0 numbers

2024-09-09 02:06 UTC, hudson-newey commented on src/components/progress-bar/progress-bar.ts
> +  public historyHeadOffset = 0;
Yeah, I too thought it was a bit weird when I came across it.

My thoughts were: I shouldn't be refactoring how history works in this PR, and we're going to remove the double buffer in a following issue as well

2024-09-09 02:14 UTC, atruskie commented on src/components/progress-bar/progress-bar.ts
> +  public historyHeadOffset = 0;
true, but you can supply a number to this component however you like

2024-09-09 04:42 UTC, nellihol requested changes
Hi Hudson, looks great! 


Some questions/suggestions:  
1. Remove border
2. Change the main background color from transparent/white to ` --oe-panel-color`
3.  Make the progress bar thinner (in my mock-up it's 10px, use a variable that suits)
4. Make the progress head segment rounded e.g. `.progress-bar > .head-segment { border-radius: var(--oe-border-rounding);`
5. Make sure the progress bar is same width as the buttons above it.  So instead of 100% of the full container I think it would look more balanced as 100% of the button console, if that makes sense?
6. Make sure you have the same spacing between the progress bar and the "Do all of the audio segments..." instructive text to make it look balanced

Here is a mock-up for my suggestions: 
![image](https://github.com/user-attachments/assets/6976933c-b858-4f71-abe7-8c8adecb64a1)

2024-09-09 06:47 UTC, hudson-newey commented
I have updated the design with from requested feedback

I have added the revised designs to the PR's description

2024-09-10 06:19 UTC, nellihol approved these changes

2024-09-11 04:36 UTC, merged